ALTER TABLE articles
  ADD COLUMN slug VARCHAR(255) UNIQUE,
  ADD COLUMN excerpt VARCHAR(500),
  ADD COLUMN cover_image VARCHAR(500),
  ADD COLUMN author_id INT REFERENCES users(id),
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;